### ISSUE TITLE
Missing AppCompatDispatcherHelper from nuget package

### ISSUE THREAD

**Issue by coddo** [jimbobbennett/JimBobBennett.MvvmLight.AppCompat#2]
Hi, your implementation for AppCompat with MVVM light is awesome!

I have one problem with the latest version of your nuget package: it doesn't contain the AppCompatDispatcherHelper class as described here: https://www.jimbobbennett.io/mvvmlight-navigation-and-appcompatactivity/ (at the bottom update note)

Can you check the package spec?

![image](https://cloud.githubusercontent.com/assets/2642265/21687171/e7c96904-d370-11e6-8cda-0c4b7fa2e83c.png)
![image](https://cloud.githubusercontent.com/assets/2642265/21687206/07d5ae9c-d371-11e6-85f5-1a05303dc307.png)

**Comment by jimbobbennett** [comment]
Weird. I've rebuilt and updated the package to support the latest frameworks and the dispatcher helper seems to now be available in version 1.1.3. Give it a whirl and let me know of any problems.

**Comment by coddo** [comment]
Hi. It's working now, thanks!
